language: php

php:
- 7.1
- 7.2
#  - hhvm

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
  - $HOME/.composer/cache

install:
- travis_retry composer self-update && composer --version
- travis_retry composer update --dev --prefer-dist --no-interaction
# install php extensions
- |
  if (php --version | grep -i HipHop > /dev/null); then
    echo "Skipping imagick and gmagick tests on HHVM"
  else
    pear config-set preferred_state beta
    printf "\n" | pecl install imagick
    # gmagick is not installed on travis currently
    #printf "\n" | pecl install gmagick
  fi
# setup application:
- |
  cp phpunit.xml.dist phpunit.xml
script:
- |
  vendor/bin/phpunit